<!--
/**
 * @category   Rukhsar
 * @package    Rukhsar_NotificationBar
 * @author     Rukhsar Manzoor (rukhsar.man@gmail.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 -->
<?php
/**
 * @see Rukhsar_NotificationBar_Block_Html_Notifications
 */
?>
<?php if ($this->displayNotifications()): ?>
    <div id="notification-bar"><div id="notification"><span class="notification-content"><?php echo $this->getNotificationContent(); ?></span><?php if($this->allowClearControl()) : ?><span class="notification-close"><a title="dismiss this notification">×</a></span><?php endif; ?></div></div>
    <?php if($this->allowClearControl()) : ?>
    <script type="text/javascript">
        $$('#notification-bar .notification-close').first().observe('click',function(event) { var callback = <?php echo ($this->isFixed() ? "function() { \$\$('body').first().setStyle({marginTop:0}); }" : "function(){}") ?>; event.element().up('#notification-bar').fade({duration:0.5, afterFinish:callback}); Mage.Cookies.set("<?php echo $this->getNotificationClearCookieName() ?>","1",new Date((new Date()).getTime() + 365*24*60*60*1000),"/"); });
    </script>
    <?php endif; ?>
<?php endif; ?>