<!--
/**
 * @category   Rukhsar
 * @package    Rukhsar_NotificationBar
 * @author     Rukhsar Manzoor (rukhsar.man@gmail.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 -->
<?php
/**
 * @see Rukhsar_NotificationBar_Block_Html_Styles
 */
?>
<?php if($this->displayNotifications()) : ?>
	<?php if($this->useDefaultStyles() || $this->isFixed()) : ?>
	<style type="text/css">
	<?php endif; ?>
	<?php if($this->useDefaultStyles()) : ?>
	    #notification-bar { text-align:center;background-color:#D75F07;color:white;line-height:normal;padding:7px 0; }
	    #notification-bar span.notification-close { background-color: #FAD163;border: 2px solid #735005;cursor: pointer;display: block;float: right;margin-right: 10px;padding-left: 4px;padding-right: 4px;text-decoration: none; }
	    #notification-bar .notification-close a { text-decoration: none; color: #735005; }
	    #notification-bar .notification-close a:hover { text-decoration: none; }
	<?php endif; ?>
	<?php if($this->isFixed()) : ?>
		#notification-bar { position: fixed;top: 0;width: 100%;z-index: 100;border-bottom: 1px solid black; }
		body { margin-top: <?php echo $this->getFixedMargin() ?>; }
	<?php endif; ?>
	<?php if($this->useDefaultStyles() || $this->isFixed()) : ?>
	</style>
	<?php endif; ?>
<?php endif; ?>